
const SENTENCES = [
  "practice makes typing faster over time",
  "small improvements lead to better results",
  "minimal websites feel clean and responsive",
  "typing every day improves muscle memory",
  "fast applications create better experiences",
  "good design focuses on simplicity and speed",
  "consistent practice helps build confidence",
  "modern interfaces should remain distraction free",
  "smooth typing requires focus and rhythm",
  "simple products often become the most popular",
  "keyboard practice improves hand coordination",
  "clean layouts help users stay focused",
  "developers should optimize for performance first",
  "daily habits create long term improvement",
  "fast loading websites improve retention",
  "minimal interfaces reduce visual fatigue",
  "coding becomes easier with consistent practice",
  "typing rhythm improves with repetition",
  "responsive websites work well on every device",
  "small details create premium experiences",
  "simple animations improve perceived quality",
  "reading carefully reduces typing mistakes",
  "steady progress matters more than perfection",
  "great products solve simple problems well",
  "lightweight websites feel faster and smoother",
  "focus leads to better typing accuracy",
  "users appreciate fast and stable interfaces",
  "short breaks help maintain concentration",
  "practice sessions should remain enjoyable",
  "smooth scrolling creates a better experience",
  "strong habits build long term consistency",
  "efficient code improves overall performance",
  "minimalism creates a calm visual experience",
  "modern tools help developers move faster",
  "quick reactions improve typing speed gradually",
  "design systems improve consistency across pages",
  "responsive design is essential for mobile users",
  "simple interactions feel more natural",
  "creative thinking improves problem solving skills",
  "fast feedback keeps users engaged",
  "good typography improves readability significantly",
  "clean colors reduce visual distractions",
  "typing games should feel smooth and relaxing",
  "efficient workflows save valuable time",
  "users prefer websites without unnecessary clutter",
  "consistent spacing improves interface quality",
  "minimal design often feels more modern",
  "smooth animations should remain subtle",
  "developers should prioritize accessibility early",
  "small updates gradually improve applications",
  "performance optimization increases user satisfaction",
  "clear layouts improve overall usability",
  "simple navigation helps users stay focused",
  "practice regularly to improve typing rhythm",
  "focused work sessions improve productivity",
  "modern browsers support advanced web features",
  "simple websites load faster on mobile devices",
  "efficient rendering improves typing responsiveness",
  "good interfaces should feel effortless",
  "high quality products focus on user experience",
  "organized codebases simplify future maintenance",
  "clean user interfaces increase readability",
  "daily typing practice improves confidence",
  "smooth interactions create premium experiences",
  "responsive layouts adapt to different screens",
  "minimal styling keeps interfaces elegant",
  "stable performance improves user trust",
  "clear typography enhances readability on mobile",
  "consistent pacing improves typing accuracy",
  "simple workflows reduce unnecessary complexity",
  "fast response times improve retention",
  "small projects help beginners learn quickly",
  "coding practice improves logical thinking",
  "subtle animations create a modern feeling",
  "good spacing improves visual hierarchy",
  "lightweight applications feel faster overall",
  "practice builds confidence over time",
  "users enjoy smooth and predictable interactions",
  "clear structure simplifies navigation",
  "minimal products often age very well",
  "web performance directly affects user engagement",
  "smooth experiences increase repeat usage",
  "responsive interfaces improve accessibility",
  "simple applications scale more effectively",
  "typing consistently improves finger memory",
  "better habits lead to stronger performance",
  "small wins motivate long term progress",
  "efficient layouts improve usability significantly",
  "focused interfaces reduce cognitive load",
  "fast websites improve search visibility",
  "smooth rendering creates a polished feeling",
  "careful practice reduces typing errors",
  "clear communication improves collaboration",
  "well optimized code improves responsiveness",
  "simple interactions create intuitive experiences",
  "consistent design improves product identity",
  "good developers value performance and simplicity",
  "responsive websites improve mobile retention",
  "modern layouts should remain visually balanced",
  "practice helps improve speed and precision",
  "lightweight pages load quickly everywhere",
  "clean interfaces help users stay productive",
  "simple systems are easier to maintain",
  "minimal websites feel elegant and modern",
  "typing tests should remain distraction free",
  "good experiences encourage repeat visits",
  "small refinements create better interfaces",
  "focused work produces stronger results",
  "consistent coding practice improves skills",
  "simple navigation improves accessibility",
  "responsive design supports every screen size",
  "smooth motion improves interface quality",
  "fast websites reduce user frustration",
  "typing rhythm improves with daily practice",
  "clear interfaces improve overall satisfaction",
  "subtle design choices create premium products",
  "minimal layouts improve reading comfort",
  "developers should test on mobile devices",
  "clean typography improves readability greatly",
  "good user experiences feel natural",
  "performance optimization should happen early",
  "simple applications often scale efficiently",
  "focused interfaces improve user engagement",
  "smooth interactions increase usability",
  "practice regularly for better consistency",
  "good habits create long term improvement",
  "minimal design highlights important content",
  "typing smoothly requires concentration and rhythm",
  "modern products prioritize responsiveness",
  "clean layouts improve visual clarity",
  "simple workflows improve productivity",
  "responsive pages adapt smoothly to mobile screens",
  "lightweight design improves overall performance",
  "daily improvement builds strong confidence",
  "clear content improves user understanding",
  "fast rendering creates smooth experiences",
  "good interfaces reduce unnecessary effort",
  "simple styling improves visual consistency",
  "organized structures simplify development workflows",
  "small improvements create noticeable results",
  "modern interfaces should remain intuitive",
  "smooth experiences encourage longer sessions",
  "responsive typography improves mobile readability",
  "focused layouts reduce visual clutter",
  "simple products remain easier to optimize",
  "clear spacing improves readability on every device",
  "efficient applications create better user experiences",
  "practice helps build reliable typing habits",
  "minimal styling keeps websites lightweight",
  "well designed systems feel easy to use",
  "fast interfaces improve user satisfaction",
  "simple interactions create smoother workflows",
  "modern web applications should remain responsive",
  "clean code improves long term maintainability",
  "consistent layouts improve usability",
  "smooth transitions enhance visual quality",
  "focused environments improve concentration",
  "responsive interfaces support accessibility goals",
  "small optimizations improve loading speed",
  "typing speed improves with repetition",
  "minimal applications reduce unnecessary distractions",
  "good typography supports comfortable reading",
  "simple navigation improves usability significantly",
  "responsive websites create better mobile experiences",
  "performance focused development improves retention",
  "smooth scrolling helps maintain focus",
  "minimalism often improves visual clarity",
  "developers should prioritize fast rendering",
  "practice sessions should remain enjoyable and calm",
  "focused interfaces support better productivity",
  "simple tools often become highly effective",
  "fast loading times improve user trust",
  "responsive layouts improve visual balance",
  "consistent practice strengthens typing memory",
  "small design details improve product quality",
  "clean interfaces improve overall readability",
  "simple systems reduce development complexity",
  "typing rhythm develops through repetition",
  "modern websites should feel effortless",
  "lightweight pages improve performance everywhere",
  "good spacing creates cleaner layouts",
  "focused workflows improve coding efficiency",
  "simple applications remain easier to maintain",
  "responsive experiences improve engagement rates",
  "minimal interfaces help users stay focused",
  "fast rendering improves perceived responsiveness",
  "consistent improvement builds stronger skills",
  "clear typography enhances visual comfort",
  "good products solve problems elegantly",
  "smooth interactions improve user satisfaction",
  "efficient rendering improves overall speed",
  "typing practice should feel rewarding",
  "clean designs create professional experiences",
  "minimal layouts support readability",
  "responsive websites adapt naturally to devices",
  "focused design improves user retention",
  "simple user flows reduce confusion",
  "fast applications encourage repeat sessions",
  "practice improves typing consistency gradually",
  "modern interfaces should remain uncluttered",
  "clear hierarchy improves navigation",
  "small refinements create polished experiences",
  "good interfaces feel smooth and stable",
  "responsive pages support mobile accessibility",
  "simple styling creates timeless interfaces",
  "focused practice leads to measurable progress",
  "efficient workflows improve development speed",
  "clean user interfaces improve satisfaction",
  "minimal applications often perform better",
  "smooth feedback improves interaction quality",
  "typing accuracy improves with concentration",
  "modern products should load quickly",
  "simple websites create calm experiences",
  "consistent coding improves technical understanding",
  "clear visuals support easier reading",
  "lightweight design improves overall usability",
  "focused layouts reduce distractions significantly",
  "responsive systems improve cross device usability",
  "fast websites help reduce bounce rates",
  "good developers value maintainable architecture",
  "simple experiences often feel more premium",
  "typing smoothly requires patience and repetition",
  "minimal visual design improves focus",
  "small optimizations create noticeable performance gains",
  "modern websites should remain accessible",
  "clean spacing improves interface readability",
  "focused interaction design improves usability",
  "responsive design creates flexible experiences",
  "smooth interfaces encourage longer engagement",
  "practice consistently to improve confidence",
  "simple navigation reduces user frustration",
  "efficient systems improve scalability",
  "minimal applications support faster loading",
  "good products prioritize clarity and speed",
  "typing performance improves with regular training",
  "clear interfaces create better experiences",
  "small changes improve overall polish",
  "responsive websites improve accessibility for everyone",
  "focused environments support deeper concentration",
  "smooth rendering creates premium interaction quality",
  "minimal websites feel modern and elegant",
  "consistent practice improves typing flow",
  "simple layouts improve content visibility",
  "fast feedback keeps interactions engaging",
  "modern design should remain distraction free",
  "lightweight pages improve mobile performance",
  "good spacing supports visual balance",
  "responsive interfaces adapt naturally to screens",
  "clean typography improves long reading sessions",
  "typing efficiently requires rhythm and focus",
  "simple products often outperform complex systems",
  "focused user experiences improve retention",
  "minimal designs reduce cognitive overload",
  "smooth motion creates polished interactions",
  "clear workflows improve productivity significantly",
  "responsive pages support modern browsing habits",
  "small improvements lead to lasting growth",
  "modern websites should remain lightweight",
  "typing practice helps improve overall accuracy",
  "clean interfaces encourage repeat usage",
  "simple applications are easier to optimize",
  "focused layouts improve readability on mobile",
  "smooth transitions create premium experiences",
  "efficient rendering improves interaction responsiveness",
  "minimal interfaces improve visual clarity",
  "fast applications feel more enjoyable",
  "clear design systems improve consistency",
  "responsive experiences support every platform",
  "practice helps develop reliable typing speed",
  "modern tools improve development workflows",
  "simple structures reduce maintenance effort",
  "clean layouts support focused interaction",
  "good interfaces should remain intuitive",
  "responsive systems improve user satisfaction",
  "minimal styling supports faster loading",
  "smooth interactions increase perceived quality",
  "typing regularly improves coordination and rhythm",
  "focused work sessions improve productivity greatly",
  "simple products often scale efficiently",
  "modern applications should remain responsive",
  "clean interfaces help reduce distractions",
  "responsive layouts improve accessibility overall",
  "small optimizations improve user experience",
  "fast websites create smoother browsing experiences",
  "minimal design creates elegant user interfaces",
  "good usability improves long term retention",
  "typing tests should remain simple and smooth",
  "clear navigation supports better usability",
  "responsive typography improves readability everywhere",
  "smooth feedback improves interaction flow",
  "focused interfaces support deeper engagement",
  "lightweight applications improve performance consistently",
  "simple experiences feel calm and polished",
  "typing practice builds long term confidence",
  "minimal products often perform extremely well",
  "responsive systems improve mobile browsing",
  "clean user experiences increase satisfaction",
  "fast interactions improve perceived responsiveness",
  "good visual hierarchy improves readability",
  "focused workflows reduce unnecessary friction",
  "simple websites should load instantly",
  "modern interfaces benefit from subtle animations",
  "typing smoothly requires steady concentration"
];
